services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    environment:
      MONGO_INITDB_DATABASE: reddit
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_ROOT_USERNAME: root
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - reddit

  mongo-express:
      image: mongo-express
      container_name: mongo-express
      restart: unless-stopped
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: secret
        ME_CONFIG_MONGODB_SERVER: mongodb
      depends_on:
        - mongodb
      networks:
        - reddit
networks:
  reddit:
    driver: bridge

volumes:
  mongodb_data: